services:
  postgres:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_DB: website
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: